### PR TITLE
2016-05-23 FIX #53

### LINKED ISSUE #53: can't get composit graphs working
Hi,

I don't know if this is relate to another issue, but I can't get composit graphs working. To me it looks like vars.graphite_keys settings in icinga2 services is totally ignored.

I tried the following setting according to documentation:

vars.graphite_keys = [ "{load1,load5,load15}" ]

From my understanding I should get 1 graph with 3 lines, but I keep getting 3 individual graphs - or am I understanding somethig wrong here ?

Even, if I try to just graph f.e. just load1 and load5 all 3 values are graphed.

I am using icinga2 2.4.7, icingaweb2 2.3.2 as well as icingaweb2-module-graphite 0.0.0.5 on debian jessie.

Any help would be appreciated.

### PR DESCRIPTION
**Pull request by sbancal**
According to my tests, this should fix issue #53.

Regards

### CODE REVIEW

**Comment by sbancal** [comment]
1. Added some tiny fixes on existing features.
2. Added graph_type = "derivative" feature.
   Useful for sensors giving increasing counters (like printer's page count, network IO bytes counter, ...).

**Comment by sbancal** [comment]
3.. Added color_list which works great in conjunction with `vars.graphite_keys`

**Comment by sbancal** [comment]
4.. Let the admin set globally the following settings :
- areaMode
- areaAlpha
- summarizeInterval
- colorList

File: library/Graphite/Grapher.php [hunk 1]
```diff
@@ -19,12 +19,18 @@ class Grapher extends GrapherHook
...
+    protected $DerivativeMacro = 'summarize(nonNegativeDerivative($target$),\'$summarizeInterval$\', \'$summarizeFunc$\')';
     protected $legacyMode = false;
     protected $graphiteKeys = array();
     protected $graphiteLabels = array();
     protected $areaMode = "all";
+    protected $graphType = "normal";
+    protected $summarizeInterval = "10min";
+    protected $summarizeFunc = "sum";
+    protected $areaAlpha = "0.1";
+    protected $colorList = "049BAF,EE1D00,04B06E,0446B0,871E10,CB315D,B06904,B0049C";
```
Comment (philiphoy) [inline library/Graphite/Grapher.php:33]: I think it would be better to avoid having properties for all the parameters e.g. the colorlist, areaalpha etc. otherwise this list will grow and grow. Perhaps if possible just add the graphite args to the template definitions?

File: README.md [hunk 2]
```diff
@@ -71,6 +72,44 @@ Composite graph definitions can get long and cumbersome, so you can define Label
...
+    graphite_area_mode = all
+    graphite_area_alpha = 0.1
+
+For details about the values, see doc here : http://graphite.readthedocs.io/en/latest/render_api.html?highlight=areaMode
+
+### Derivative graphs
+It is possible to plot derivative graphs instead of the measured values. This is useful for sensors giving increasing counters (like printer's page count, network IO bytes counter, ...). You can set it by adding the following to your Service definition.
+
+    vars.graphite.graph_type = "derivative" // default : "normal"
+
```
Comment (philiphoy) [inline README.md:92]: A more flexible approach here might be to have a $target$ override. 

`vars.graphite.target = "summarize(nonNegativeDerivative($target$),'hour, 'sum')"`

Otherwise you can only set one derivative for all graphs.

File: library/Graphite/Grapher.php (hunk 1 above)
Comment (sbancal) [inline library/Graphite/Grapher.php:33]: Hi,
I agree that this would make the code more concise, but in our case, we find it useful to be able to overwrite these settings, case by case in Icinga's settings.
For example, the colorList is given by default to match the expected look-n-feel in Icinga's web pages. This can be set, as you say, in the template definitions. But for some graphs, we think useful to choose other colors. Network_IO check for instance is attributed blue and red colors (respectively for RX and TX).
This wouldn’t be possible if that settings is only set in the template definition.

What do you think?

File: README.md (hunk 2 above)
Comment (sbancal) [inline README.md:92]: Ok ...
This is a setting that should be set in Icinga's config.
I just thought it would be easier to set a variable to a single word, instead than to an expression (that could be miswritten).

In fact, the type of function can already be customized with the 2 variables : `summarize_interval` and `summarize_func` .

Do you see other ways to customize a derivative graph? Or you mean ... something other than derivative graph?

File: library/Graphite/Grapher.php (hunk 1 above)
Comment (sbancal) [inline library/Graphite/Grapher.php:33]: Here is an example of a Network_IO graph in which it's useful to set different colors than default.
render_netio

File: README.md (hunk 2 above)
Comment (sashman) [reply README.md:92]: Hey @sbancal, sorry for the delayed response. Could you please help me get caught up here, is the conversation happening here still relevant?

Comment (sbancal) [reply README.md:92]: Hi @sashman , glad to hear a response here.
No, the conversation didn't go any further. To me, it's better to go this way for now. It's flexible to be customized with `summarize_interval` and `summarize_func`, it's robust because admins don't have to set the `$target$` function (which would result in much of verbose-duplicated config) and we can even later introduce new `graph_types`.

Comment (sashman) [reply README.md:92]: Personally I'd go with @philiphoy suggestion, but I think it's alright to bring this in for now. I'm guessing this still functions as expected? Apologies I'm still getting caught up with this...

Comment (sbancal) [reply README.md:92]: Yes, this is how we use it for now on our production.

**Comment by sashman** [comment]
Cool thanks!
